# Generated by Django 2.2.7 on 2020-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question_papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('examination', models.CharField(max_length=40)),
                ('paper', models.FileField(blank=True, null=True, upload_to='preqps')),
            ],
        ),
    ]
