# Generated by Django 2.2.7 on 2020-05-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_papers',
            name='university',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question_papers',
            name='examination',
            field=models.CharField(max_length=100),
        ),
    ]
